import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { BarChart3, ArrowLeft } from "lucide-react";
import { ThemeToggle } from "@/components/ThemeToggle";

const Privacy = () => {
  const navigate = useNavigate();
  useEffect(() => { document.title = "Privacy Policy | Validifier"; }, []);

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-2 cursor-pointer" onClick={() => navigate("/")}>
            <BarChart3 className="h-8 w-8 text-primary" />
            <span className="text-2xl font-bold bg-gradient-hero bg-clip-text text-transparent">Validifier</span>
          </div>
          <div className="flex items-center space-x-2">
            <ThemeToggle />
            <Button variant="ghost" onClick={() => navigate(-1 as any)}>
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back
            </Button>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-4 py-16 max-w-3xl">
        <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-muted-foreground mb-10">Last updated: March 5, 2026</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8 text-foreground/90">
          <section>
            <h2 className="text-2xl font-semibold text-foreground">1. Information We Collect</h2>
            <p>When you use Validifier, we collect the following types of information:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Account information:</strong> Email address, full name, and authentication credentials when you create an account.</li>
              <li><strong>Business ideas & project data:</strong> Project names, descriptions, website URLs, and industry selections you submit for validation.</li>
              <li><strong>AI-generated reports:</strong> The validation reports, chat conversations, and analysis results generated by our AI system.</li>
              <li><strong>Usage data:</strong> Pages visited, features used, AI credits consumed, and general interaction patterns (subject to your cookie consent preferences).</li>
              <li><strong>Payment information:</strong> Billing details are processed securely by Stripe. We store only your Stripe customer ID — never your card details.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">2. How We Use Your Information</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>To provide the service:</strong> Generating validation reports, powering the Cora AI chat, and managing your projects.</li>
              <li><strong>To improve our AI models:</strong> We may use anonymized, aggregated data to improve our analysis quality. Your specific business ideas are <strong>never</strong> shared with third parties or used to train external AI models.</li>
              <li><strong>Third-party AI processing:</strong> Your project data is sent to AI model providers (Google Gemini, OpenAI) for report generation. These providers process data according to their own privacy policies and do not retain your data for model training under our API agreements.</li>
              <li><strong>Analytics:</strong> With your consent, we use analytics to understand how users interact with the platform so we can improve the experience.</li>
              <li><strong>Communication:</strong> To send transactional emails (report completion, account changes) and, optionally, product updates.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">3. Data Retention</h2>
            <p>We retain your data for as long as your account is active. Specifically:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Account & profile data:</strong> Retained until you delete your account.</li>
              <li><strong>Projects & reports:</strong> Retained until you delete individual projects or your entire account.</li>
              <li><strong>Chat conversations:</strong> Retained with their associated project.</li>
              <li><strong>Analytics & usage logs:</strong> Anonymized and retained for up to 24 months for service improvement.</li>
              <li><strong>Payment records:</strong> Retained as required by financial regulations (typically 7 years).</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">4. Data Sharing</h2>
            <p>We do not sell your personal data. We share data only with:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>AI providers</strong> (Google, OpenAI) — for report generation, under strict API data processing agreements.</li>
              <li><strong>Stripe</strong> — for payment processing.</li>
              <li><strong>Hosting infrastructure</strong> — to operate the service securely.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">5. Your Rights</h2>
            <p>Under GDPR, CCPA, and similar regulations, you have the right to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Access</strong> your personal data.</li>
              <li><strong>Correct</strong> inaccurate data via your Settings page.</li>
              <li><strong>Delete</strong> your account and all associated data. You can do this from{" "}
                <button onClick={() => navigate("/settings")} className="text-primary underline underline-offset-2 hover:text-primary/80">
                  Settings → Delete Account
                </button>.
              </li>
              <li><strong>Export</strong> your reports using the Share & Export options available on each report.</li>
              <li><strong>Withdraw consent</strong> for analytics cookies at any time by clearing your browser's local storage.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">6. Cookies</h2>
            <p>We use essential cookies to operate the service (authentication, session management) and optional analytics cookies (with your consent) to understand usage patterns. You can manage your cookie preferences at any time via the cookie consent banner.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">7. Security</h2>
            <p>We implement industry-standard security measures including encryption in transit (TLS), secure authentication, row-level security policies on all database tables, and rate limiting on API endpoints.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">8. Contact Us</h2>
            <p>For privacy-related questions, data access requests, or concerns:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Email: <a href="mailto:privacy@validifier.com" className="text-primary underline underline-offset-2">privacy@validifier.com</a></li>
              <li>General support: <a href="mailto:support@validifier.com" className="text-primary underline underline-offset-2">support@validifier.com</a></li>
            </ul>
            <p className="mt-2">We aim to respond to all privacy-related requests within 30 days.</p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
