import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { BarChart3, ArrowLeft } from "lucide-react";
import { ThemeToggle } from "@/components/ThemeToggle";

const Terms = () => {
  const navigate = useNavigate();
  useEffect(() => { document.title = "Terms of Service | Validifier"; }, []);

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-2 cursor-pointer" onClick={() => navigate("/")}>
            <BarChart3 className="h-8 w-8 text-primary" />
            <span className="text-2xl font-bold bg-gradient-hero bg-clip-text text-transparent">Validifier</span>
          </div>
          <div className="flex items-center space-x-2">
            <ThemeToggle />
            <Button variant="ghost" onClick={() => navigate(-1 as any)}>
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back
            </Button>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-4 py-16 max-w-3xl">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-10">Last updated: March 5, 2026</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8 text-foreground/90">
          <section>
            <h2 className="text-2xl font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p>By accessing or using Validifier ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">2. Description of Service</h2>
            <p>Validifier is an AI-powered business idea validation platform. We generate analysis reports, market research, and strategic insights using artificial intelligence to help entrepreneurs evaluate their business concepts.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">3. AI-Generated Content Disclaimer</h2>
            <p className="font-medium text-destructive/80">All validation reports, analysis, recommendations, and chat responses provided by Validifier are generated by artificial intelligence and are intended for informational purposes only.</p>
            <p>This content:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Should not</strong> be considered professional business, financial, legal, or investment advice.</li>
              <li><strong>May contain</strong> inaccuracies, outdated information, or errors inherent to AI-generated content.</li>
              <li><strong>Should not</strong> be the sole basis for any business, financial, or legal decisions.</li>
              <li><strong>Is not</strong> a substitute for consultation with qualified professionals in relevant fields.</li>
            </ul>
            <p>You acknowledge that you use AI-generated content at your own risk and that Validifier bears no responsibility for decisions made based on this content.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">4. Acceptable Use Policy</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
              <li>Submit false, misleading, or fraudulent information.</li>
              <li>Attempt to circumvent rate limits, credit systems, or other technical restrictions.</li>
              <li>Use automated tools, bots, or scripts to access the Service without authorization.</li>
              <li>Reverse-engineer, decompile, or attempt to extract source code from the Service.</li>
              <li>Resell, redistribute, or commercially exploit AI-generated reports without authorization.</li>
              <li>Use the Service to generate content that is harmful, abusive, or violates third-party rights.</li>
            </ul>
            <p>Violation of this policy may result in immediate account termination without refund.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">5. Credits & Billing</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>AI Credits:</strong> The Service operates on a credit-based system. Each AI operation (report generation, chat messages, website analysis) consumes credits from your monthly allocation.</li>
              <li><strong>Free tier:</strong> Includes a limited number of monthly credits that reset each billing cycle. Unused credits do not carry over.</li>
              <li><strong>Paid plans:</strong> Provide additional credits and features. Subscriptions are billed monthly or annually as selected at checkout.</li>
              <li><strong>Refunds:</strong> Subscription fees are non-refundable except where required by law. If you encounter a technical issue preventing credit usage, contact support for credit restoration.</li>
              <li><strong>Cancellation:</strong> You may cancel your subscription at any time. Access continues until the end of the current billing period.</li>
              <li><strong>Price changes:</strong> We reserve the right to modify pricing with 30 days' notice to active subscribers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">6. Intellectual Property</h2>
            <p>You retain ownership of the business ideas and descriptions you submit. AI-generated reports are provided to you under a non-exclusive license for your personal and business use. The Validifier platform, brand, and underlying technology remain our intellectual property.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">7. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Validifier is provided "as is" and "as available" without warranties of any kind, express or implied.</li>
              <li>We do not guarantee the accuracy, completeness, or reliability of any AI-generated content.</li>
              <li>We are not liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.</li>
              <li>Our total liability for any claim related to the Service shall not exceed the amount you paid us in the 12 months preceding the claim.</li>
              <li>We are not responsible for any business decisions, investments, or actions taken based on information provided by the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">8. Account Termination</h2>
            <p>We reserve the right to suspend or terminate your account at our discretion if you violate these terms. You may delete your account at any time from{" "}
              <button onClick={() => navigate("/settings")} className="text-primary underline underline-offset-2 hover:text-primary/80">
                Settings → Delete Account
              </button>, which will permanently remove all your data as described in our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">9. Changes to Terms</h2>
            <p>We may update these terms from time to time. Material changes will be communicated via email or an in-app notification. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground">10. Contact</h2>
            <p>For questions about these terms:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Email: <a href="mailto:legal@validifier.com" className="text-primary underline underline-offset-2">legal@validifier.com</a></li>
              <li>General support: <a href="mailto:support@validifier.com" className="text-primary underline underline-offset-2">support@validifier.com</a></li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Terms;
